Fix build on v5.12 (find_module unexport)
Since find_module() is unexported in v5.12 use own compat
implementation. Error message:

    CC [M]  ipt-netflow/ipt_NETFLOW.o
    MODPOST ipt-netflow/Module.symvers
  ERROR: modpost: "find_module" [ipt-netflow/ipt_NETFLOW.ko] undefined!
  scripts/Makefile.modpost:150: recipe for target 'ipt-netflow/Module.symvers' failed